language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi'

matrix:
  allow_failures:
    - php: hhvm
